//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraticeManagement.ConfigurationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationService.IConfigurationService")]
    public interface IConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetAllEmailTemplates", ReplyAction="http://tempuri.org/IConfigurationService/GetAllEmailTemplatesResponse")]
        DataTransferObjects.EmailTemplate[] GetAllEmailTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/EmailTemplateGetByName", ReplyAction="http://tempuri.org/IConfigurationService/EmailTemplateGetByNameResponse")]
        DataTransferObjects.EmailTemplate EmailTemplateGetByName(string emailTemplateName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/UpdateEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/UpdateEmailTemplateResponse")]
        bool UpdateEmailTemplate(DataTransferObjects.EmailTemplate template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/AddEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/AddEmailTemplateResponse")]
        bool AddEmailTemplate(DataTransferObjects.EmailTemplate template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/DeleteEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/DeleteEmailTemplateResponse")]
        bool DeleteEmailTemplate(int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetEmailData", ReplyAction="http://tempuri.org/IConfigurationService/GetEmailDataResponse")]
        DataTransferObjects.EmailData GetEmailData(DataTransferObjects.ContextObjects.EmailContext emailContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetCompanyLogoData", ReplyAction="http://tempuri.org/IConfigurationService/GetCompanyLogoDataResponse")]
        DataTransferObjects.CompanyLogo GetCompanyLogoData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveCompanyLogoData", ReplyAction="http://tempuri.org/IConfigurationService/SaveCompanyLogoDataResponse")]
        void SaveCompanyLogoData(string title, string imagename, string imagePath, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveResourceKeyValuePairs", ReplyAction="http://tempuri.org/IConfigurationService/SaveResourceKeyValuePairsResponse")]
        void SaveResourceKeyValuePairs(DataTransferObjects.SettingsType settingType, System.Collections.Generic.Dictionary<string, string> dictionary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveResourceKeyValuePairItem", ReplyAction="http://tempuri.org/IConfigurationService/SaveResourceKeyValuePairItemResponse")]
        bool SaveResourceKeyValuePairItem(DataTransferObjects.SettingsType settingType, string key, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetResourceKeyValuePairs", ReplyAction="http://tempuri.org/IConfigurationService/GetResourceKeyValuePairsResponse")]
        System.Collections.Generic.Dictionary<string, string> GetResourceKeyValuePairs(DataTransferObjects.SettingsType settingType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/VerifySMTPSettings", ReplyAction="http://tempuri.org/IConfigurationService/VerifySMTPSettingsResponse")]
        bool VerifySMTPSettings(string MailServer, int PortNumber, bool EnableSSl, string UserName, string Password, string PMSupportEmailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveMarginInfoDetail", ReplyAction="http://tempuri.org/IConfigurationService/SaveMarginInfoDetailResponse")]
        void SaveMarginInfoDetail(DataTransferObjects.Triple<DataTransferObjects.DefaultGoalType, DataTransferObjects.Triple<DataTransferObjects.SettingsType, string, string>, DataTransferObjects.ClientMarginColorInfo[]>[] marginInfoList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetMarginColorInfoDefaults", ReplyAction="http://tempuri.org/IConfigurationService/GetMarginColorInfoDefaultsResponse")]
        DataTransferObjects.ClientMarginColorInfo[] GetMarginColorInfoDefaults(DataTransferObjects.DefaultGoalType goalType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SavePracticesIsNotesRequiredDetails", ReplyAction="http://tempuri.org/IConfigurationService/SavePracticesIsNotesRequiredDetailsRespo" +
            "nse")]
        void SavePracticesIsNotesRequiredDetails(string isNotesRequiredPracticeIdsList, string isNotesExemptedPracticeIdsList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveQuickLinksForDashBoard", ReplyAction="http://tempuri.org/IConfigurationService/SaveQuickLinksForDashBoardResponse")]
        void SaveQuickLinksForDashBoard(string linkNameList, string virtualPathList, DataTransferObjects.DashBoardType dashBoardType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetQuickLinksByDashBoardType", ReplyAction="http://tempuri.org/IConfigurationService/GetQuickLinksByDashBoardTypeResponse")]
        DataTransferObjects.QuickLinks[] GetQuickLinksByDashBoardType(DataTransferObjects.DashBoardType dashBoardtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/DeleteQuickLinkById", ReplyAction="http://tempuri.org/IConfigurationService/DeleteQuickLinkByIdResponse")]
        void DeleteQuickLinkById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveAnnouncement", ReplyAction="http://tempuri.org/IConfigurationService/SaveAnnouncementResponse")]
        void SaveAnnouncement(string text, string richText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetLatestAnnouncement", ReplyAction="http://tempuri.org/IConfigurationService/GetLatestAnnouncementResponse")]
        string GetLatestAnnouncement();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetAllDomains", ReplyAction="http://tempuri.org/IConfigurationService/GetAllDomainsResponse")]
        string[] GetAllDomains();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SendResourceExceptionReportsEmail", ReplyAction="http://tempuri.org/IConfigurationService/SendResourceExceptionReportsEmailRespons" +
            "e")]
        void SendResourceExceptionReportsEmail(System.DateTime startDate, System.DateTime endDate, byte[] attachmentByteArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetRecruitingMetrics", ReplyAction="http://tempuri.org/IConfigurationService/GetRecruitingMetricsResponse")]
        DataTransferObjects.RecruitingMetrics[] GetRecruitingMetrics(System.Nullable<int> recruitingMetricsTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveRecruitingMetrics", ReplyAction="http://tempuri.org/IConfigurationService/SaveRecruitingMetricsResponse")]
        void SaveRecruitingMetrics(DataTransferObjects.RecruitingMetrics metric);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/RecruitingMetricsDelete", ReplyAction="http://tempuri.org/IConfigurationService/RecruitingMetricsDeleteResponse")]
        void RecruitingMetricsDelete(int recruitingMetricId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/RecruitingMetricsInsert", ReplyAction="http://tempuri.org/IConfigurationService/RecruitingMetricsInsertResponse")]
        void RecruitingMetricsInsert(DataTransferObjects.RecruitingMetrics metrics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SendRecruitingMetricsReportEmail", ReplyAction="http://tempuri.org/IConfigurationService/SendRecruitingMetricsReportEmailResponse" +
            "")]
        void SendRecruitingMetricsReportEmail(System.DateTime startDate, System.DateTime endDate, byte[] attachmentByteArray);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetLockoutDetails", ReplyAction="http://tempuri.org/IConfigurationService/GetLockoutDetailsResponse")]
        DataTransferObjects.Lockout[] GetLockoutDetails(System.Nullable<int> lockoutPageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/SaveLockoutDetails", ReplyAction="http://tempuri.org/IConfigurationService/SaveLockoutDetailsResponse")]
        void SaveLockoutDetails(string lockoutXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetLocations", ReplyAction="http://tempuri.org/IConfigurationService/GetLocationsResponse")]
        DataTransferObjects.Location[] GetLocations();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationServiceChannel : PraticeManagement.ConfigurationService.IConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<PraticeManagement.ConfigurationService.IConfigurationService>, PraticeManagement.ConfigurationService.IConfigurationService {
        
        public ConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTransferObjects.EmailTemplate[] GetAllEmailTemplates() {
            return base.Channel.GetAllEmailTemplates();
        }
        
        public DataTransferObjects.EmailTemplate EmailTemplateGetByName(string emailTemplateName) {
            return base.Channel.EmailTemplateGetByName(emailTemplateName);
        }
        
        public bool UpdateEmailTemplate(DataTransferObjects.EmailTemplate template) {
            return base.Channel.UpdateEmailTemplate(template);
        }
        
        public bool AddEmailTemplate(DataTransferObjects.EmailTemplate template) {
            return base.Channel.AddEmailTemplate(template);
        }
        
        public bool DeleteEmailTemplate(int templateId) {
            return base.Channel.DeleteEmailTemplate(templateId);
        }
        
        public DataTransferObjects.EmailData GetEmailData(DataTransferObjects.ContextObjects.EmailContext emailContext) {
            return base.Channel.GetEmailData(emailContext);
        }
        
        public DataTransferObjects.CompanyLogo GetCompanyLogoData() {
            return base.Channel.GetCompanyLogoData();
        }
        
        public void SaveCompanyLogoData(string title, string imagename, string imagePath, byte[] data) {
            base.Channel.SaveCompanyLogoData(title, imagename, imagePath, data);
        }
        
        public void SaveResourceKeyValuePairs(DataTransferObjects.SettingsType settingType, System.Collections.Generic.Dictionary<string, string> dictionary) {
            base.Channel.SaveResourceKeyValuePairs(settingType, dictionary);
        }
        
        public bool SaveResourceKeyValuePairItem(DataTransferObjects.SettingsType settingType, string key, string value) {
            return base.Channel.SaveResourceKeyValuePairItem(settingType, key, value);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetResourceKeyValuePairs(DataTransferObjects.SettingsType settingType) {
            return base.Channel.GetResourceKeyValuePairs(settingType);
        }
        
        public bool VerifySMTPSettings(string MailServer, int PortNumber, bool EnableSSl, string UserName, string Password, string PMSupportEmailAddress) {
            return base.Channel.VerifySMTPSettings(MailServer, PortNumber, EnableSSl, UserName, Password, PMSupportEmailAddress);
        }
        
        public void SaveMarginInfoDetail(DataTransferObjects.Triple<DataTransferObjects.DefaultGoalType, DataTransferObjects.Triple<DataTransferObjects.SettingsType, string, string>, DataTransferObjects.ClientMarginColorInfo[]>[] marginInfoList) {
            base.Channel.SaveMarginInfoDetail(marginInfoList);
        }
        
        public DataTransferObjects.ClientMarginColorInfo[] GetMarginColorInfoDefaults(DataTransferObjects.DefaultGoalType goalType) {
            return base.Channel.GetMarginColorInfoDefaults(goalType);
        }
        
        public void SavePracticesIsNotesRequiredDetails(string isNotesRequiredPracticeIdsList, string isNotesExemptedPracticeIdsList) {
            base.Channel.SavePracticesIsNotesRequiredDetails(isNotesRequiredPracticeIdsList, isNotesExemptedPracticeIdsList);
        }
        
        public void SaveQuickLinksForDashBoard(string linkNameList, string virtualPathList, DataTransferObjects.DashBoardType dashBoardType) {
            base.Channel.SaveQuickLinksForDashBoard(linkNameList, virtualPathList, dashBoardType);
        }
        
        public DataTransferObjects.QuickLinks[] GetQuickLinksByDashBoardType(DataTransferObjects.DashBoardType dashBoardtype) {
            return base.Channel.GetQuickLinksByDashBoardType(dashBoardtype);
        }
        
        public void DeleteQuickLinkById(int id) {
            base.Channel.DeleteQuickLinkById(id);
        }
        
        public void SaveAnnouncement(string text, string richText) {
            base.Channel.SaveAnnouncement(text, richText);
        }
        
        public string GetLatestAnnouncement() {
            return base.Channel.GetLatestAnnouncement();
        }
        
        public string[] GetAllDomains() {
            return base.Channel.GetAllDomains();
        }
        
        public void SendResourceExceptionReportsEmail(System.DateTime startDate, System.DateTime endDate, byte[] attachmentByteArray) {
            base.Channel.SendResourceExceptionReportsEmail(startDate, endDate, attachmentByteArray);
        }
        
        public DataTransferObjects.RecruitingMetrics[] GetRecruitingMetrics(System.Nullable<int> recruitingMetricsTypeId) {
            return base.Channel.GetRecruitingMetrics(recruitingMetricsTypeId);
        }
        
        public void SaveRecruitingMetrics(DataTransferObjects.RecruitingMetrics metric) {
            base.Channel.SaveRecruitingMetrics(metric);
        }
        
        public void RecruitingMetricsDelete(int recruitingMetricId) {
            base.Channel.RecruitingMetricsDelete(recruitingMetricId);
        }
        
        public void RecruitingMetricsInsert(DataTransferObjects.RecruitingMetrics metrics) {
            base.Channel.RecruitingMetricsInsert(metrics);
        }
        
        public void SendRecruitingMetricsReportEmail(System.DateTime startDate, System.DateTime endDate, byte[] attachmentByteArray) {
            base.Channel.SendRecruitingMetricsReportEmail(startDate, endDate, attachmentByteArray);
        }
        
        public DataTransferObjects.Lockout[] GetLockoutDetails(System.Nullable<int> lockoutPageId) {
            return base.Channel.GetLockoutDetails(lockoutPageId);
        }
        
        public void SaveLockoutDetails(string lockoutXML) {
            base.Channel.SaveLockoutDetails(lockoutXML);
        }
        
        public DataTransferObjects.Location[] GetLocations() {
            return base.Channel.GetLocations();
        }
    }
}

