//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraticeManagement.MembershipService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipUser", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Security")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipCreateStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipUserCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipPasswordFormat))]
    public partial class MembershipUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _CommentField;
        
        private System.DateTime _CreationDateField;
        
        private string _EmailField;
        
        private bool _IsApprovedField;
        
        private bool _IsLockedOutField;
        
        private System.DateTime _LastActivityDateField;
        
        private System.DateTime _LastLockoutDateField;
        
        private System.DateTime _LastLoginDateField;
        
        private System.DateTime _LastPasswordChangedDateField;
        
        private string _PasswordQuestionField;
        
        private string _ProviderNameField;
        
        private object _ProviderUserKeyField;
        
        private string _UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Comment {
            get {
                return this._CommentField;
            }
            set {
                if ((object.ReferenceEquals(this._CommentField, value) != true)) {
                    this._CommentField = value;
                    this.RaisePropertyChanged("_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _CreationDate {
            get {
                return this._CreationDateField;
            }
            set {
                if ((this._CreationDateField.Equals(value) != true)) {
                    this._CreationDateField = value;
                    this.RaisePropertyChanged("_CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Email {
            get {
                return this._EmailField;
            }
            set {
                if ((object.ReferenceEquals(this._EmailField, value) != true)) {
                    this._EmailField = value;
                    this.RaisePropertyChanged("_Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _IsApproved {
            get {
                return this._IsApprovedField;
            }
            set {
                if ((this._IsApprovedField.Equals(value) != true)) {
                    this._IsApprovedField = value;
                    this.RaisePropertyChanged("_IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _IsLockedOut {
            get {
                return this._IsLockedOutField;
            }
            set {
                if ((this._IsLockedOutField.Equals(value) != true)) {
                    this._IsLockedOutField = value;
                    this.RaisePropertyChanged("_IsLockedOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _LastActivityDate {
            get {
                return this._LastActivityDateField;
            }
            set {
                if ((this._LastActivityDateField.Equals(value) != true)) {
                    this._LastActivityDateField = value;
                    this.RaisePropertyChanged("_LastActivityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _LastLockoutDate {
            get {
                return this._LastLockoutDateField;
            }
            set {
                if ((this._LastLockoutDateField.Equals(value) != true)) {
                    this._LastLockoutDateField = value;
                    this.RaisePropertyChanged("_LastLockoutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _LastLoginDate {
            get {
                return this._LastLoginDateField;
            }
            set {
                if ((this._LastLoginDateField.Equals(value) != true)) {
                    this._LastLoginDateField = value;
                    this.RaisePropertyChanged("_LastLoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime _LastPasswordChangedDate {
            get {
                return this._LastPasswordChangedDateField;
            }
            set {
                if ((this._LastPasswordChangedDateField.Equals(value) != true)) {
                    this._LastPasswordChangedDateField = value;
                    this.RaisePropertyChanged("_LastPasswordChangedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _PasswordQuestion {
            get {
                return this._PasswordQuestionField;
            }
            set {
                if ((object.ReferenceEquals(this._PasswordQuestionField, value) != true)) {
                    this._PasswordQuestionField = value;
                    this.RaisePropertyChanged("_PasswordQuestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _ProviderName {
            get {
                return this._ProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this._ProviderNameField, value) != true)) {
                    this._ProviderNameField = value;
                    this.RaisePropertyChanged("_ProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object _ProviderUserKey {
            get {
                return this._ProviderUserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this._ProviderUserKeyField, value) != true)) {
                    this._ProviderUserKeyField = value;
                    this.RaisePropertyChanged("_ProviderUserKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _UserName {
            get {
                return this._UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this._UserNameField, value) != true)) {
                    this._UserNameField = value;
                    this.RaisePropertyChanged("_UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipCreateStatus", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Security")]
    public enum MembershipCreateStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidQuestion = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAnswer = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateUserName = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateEmail = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserRejected = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidProviderUserKey = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateProviderUserKey = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProviderError = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipUserCollection", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Security")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipUser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipCreateStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PraticeManagement.MembershipService.MembershipPasswordFormat))]
    public partial class MembershipUserCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<object, object> _IndicesField;
        
        private bool _ReadOnlyField;
        
        private object[] _ValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.Dictionary<object, object> _Indices {
            get {
                return this._IndicesField;
            }
            set {
                if ((object.ReferenceEquals(this._IndicesField, value) != true)) {
                    this._IndicesField = value;
                    this.RaisePropertyChanged("_Indices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool _ReadOnly {
            get {
                return this._ReadOnlyField;
            }
            set {
                if ((this._ReadOnlyField.Equals(value) != true)) {
                    this._ReadOnlyField = value;
                    this.RaisePropertyChanged("_ReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object[] _Values {
            get {
                return this._ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this._ValuesField, value) != true)) {
                    this._ValuesField = value;
                    this.RaisePropertyChanged("_Values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MembershipPasswordFormat", Namespace="http://schemas.datacontract.org/2004/07/System.Web.Security")]
    public enum MembershipPasswordFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Clear = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hashed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Encrypted = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MembershipService.IMembershipService")]
    public interface IMembershipService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetApplicationName", ReplyAction="http://tempuri.org/IMembershipService/GetApplicationNameResponse")]
        string GetApplicationName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/SetApplicationName", ReplyAction="http://tempuri.org/IMembershipService/SetApplicationNameResponse")]
        void SetApplicationName(string applicationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/ChangePassword", ReplyAction="http://tempuri.org/IMembershipService/ChangePasswordResponse")]
        bool ChangePassword(string username, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/ChangePasswordQuestionAndAnswer", ReplyAction="http://tempuri.org/IMembershipService/ChangePasswordQuestionAndAnswerResponse")]
        bool ChangePasswordQuestionAndAnswer(string username, string password, string newPasswordQuestion, string newPasswordAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/CreateUser", ReplyAction="http://tempuri.org/IMembershipService/CreateUserResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipCreateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipPasswordFormat))]
        System.Web.Security.MembershipUser CreateUser(out System.Web.Security.MembershipCreateStatus status, string username, string password, string email, string passwordQuestion, string passwordAnswer, bool isApproved, object providerUserKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/DeleteUser", ReplyAction="http://tempuri.org/IMembershipService/DeleteUserResponse")]
        bool DeleteUser(string username, bool deleteAllRelatedData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetEnablePasswordReset", ReplyAction="http://tempuri.org/IMembershipService/GetEnablePasswordResetResponse")]
        bool GetEnablePasswordReset();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetEnablePasswordRetrieval", ReplyAction="http://tempuri.org/IMembershipService/GetEnablePasswordRetrievalResponse")]
        bool GetEnablePasswordRetrieval();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/FindUsersByEmail", ReplyAction="http://tempuri.org/IMembershipService/FindUsersByEmailResponse")]
        System.Web.Security.MembershipUserCollection FindUsersByEmail(out int totalRecords, string emailToMatch, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/FindUsersByName", ReplyAction="http://tempuri.org/IMembershipService/FindUsersByNameResponse")]
        System.Web.Security.MembershipUserCollection FindUsersByName(out int totalRecords, string usernameToMatch, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetAllUsers", ReplyAction="http://tempuri.org/IMembershipService/GetAllUsersResponse")]
        System.Web.Security.MembershipUserCollection GetAllUsers(out int totalRecords, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetNumberOfUsersOnline", ReplyAction="http://tempuri.org/IMembershipService/GetNumberOfUsersOnlineResponse")]
        int GetNumberOfUsersOnline();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetPassword", ReplyAction="http://tempuri.org/IMembershipService/GetPasswordResponse")]
        string GetPassword(string username, string passwordAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetUser", ReplyAction="http://tempuri.org/IMembershipService/GetUserResponse")]
        System.Web.Security.MembershipUser GetUser(string username, bool userIsOnline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetUserByProviderUserKey", ReplyAction="http://tempuri.org/IMembershipService/GetUserByProviderUserKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<object, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipUser))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipCreateStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipUserCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Web.Security.MembershipPasswordFormat))]
        System.Web.Security.MembershipUser GetUserByProviderUserKey(object providerUserKey, bool userIsOnline);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetUserNameByEmail", ReplyAction="http://tempuri.org/IMembershipService/GetUserNameByEmailResponse")]
        string GetUserNameByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetMaxInvalidPasswordAttempts", ReplyAction="http://tempuri.org/IMembershipService/GetMaxInvalidPasswordAttemptsResponse")]
        int GetMaxInvalidPasswordAttempts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetMinRequiredNonAlphanumericCharacters", ReplyAction="http://tempuri.org/IMembershipService/GetMinRequiredNonAlphanumericCharactersResp" +
            "onse")]
        int GetMinRequiredNonAlphanumericCharacters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetMinRequiredPasswordLength", ReplyAction="http://tempuri.org/IMembershipService/GetMinRequiredPasswordLengthResponse")]
        int GetMinRequiredPasswordLength();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetPasswordAttemptWindow", ReplyAction="http://tempuri.org/IMembershipService/GetPasswordAttemptWindowResponse")]
        int GetPasswordAttemptWindow();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetPasswordFormat", ReplyAction="http://tempuri.org/IMembershipService/GetPasswordFormatResponse")]
        System.Web.Security.MembershipPasswordFormat GetPasswordFormat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetPasswordStrengthRegularExpression", ReplyAction="http://tempuri.org/IMembershipService/GetPasswordStrengthRegularExpressionRespons" +
            "e")]
        string GetPasswordStrengthRegularExpression();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetRequiresQuestionAndAnswer", ReplyAction="http://tempuri.org/IMembershipService/GetRequiresQuestionAndAnswerResponse")]
        bool GetRequiresQuestionAndAnswer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/GetRequiresUniqueEmail", ReplyAction="http://tempuri.org/IMembershipService/GetRequiresUniqueEmailResponse")]
        bool GetRequiresUniqueEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/ResetPassword", ReplyAction="http://tempuri.org/IMembershipService/ResetPasswordResponse")]
        string ResetPassword(string username, string answer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/UnlockUser", ReplyAction="http://tempuri.org/IMembershipService/UnlockUserResponse")]
        bool UnlockUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMembershipService/UpdateUser", ReplyAction="http://tempuri.org/IMembershipService/UpdateUserResponse")]
        void UpdateUser(System.Web.Security.MembershipUser user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMembershipServiceChannel : PraticeManagement.MembershipService.IMembershipService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MembershipServiceClient : System.ServiceModel.ClientBase<PraticeManagement.MembershipService.IMembershipService>, PraticeManagement.MembershipService.IMembershipService {
        
        public MembershipServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MembershipServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MembershipServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetApplicationName() {
            return base.Channel.GetApplicationName();
        }
        
        public void SetApplicationName(string applicationName) {
            base.Channel.SetApplicationName(applicationName);
        }
        
        public bool ChangePassword(string username, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(username, oldPassword, newPassword);
        }
        
        public bool ChangePasswordQuestionAndAnswer(string username, string password, string newPasswordQuestion, string newPasswordAnswer) {
            return base.Channel.ChangePasswordQuestionAndAnswer(username, password, newPasswordQuestion, newPasswordAnswer);
        }

        public System.Web.Security.MembershipUser CreateUser(out System.Web.Security.MembershipCreateStatus status, string username, string password, string email, string passwordQuestion, string passwordAnswer, bool isApproved, object providerUserKey)
        {
            return base.Channel.CreateUser(out status, username, password, email, passwordQuestion, passwordAnswer, isApproved, providerUserKey);
        }
        
        public bool DeleteUser(string username, bool deleteAllRelatedData) {
            return base.Channel.DeleteUser(username, deleteAllRelatedData);
        }
        
        public bool GetEnablePasswordReset() {
            return base.Channel.GetEnablePasswordReset();
        }
        
        public bool GetEnablePasswordRetrieval() {
            return base.Channel.GetEnablePasswordRetrieval();
        }

        public System.Web.Security.MembershipUserCollection FindUsersByEmail(out int totalRecords, string emailToMatch, int pageIndex, int pageSize)
        {
            return base.Channel.FindUsersByEmail(out totalRecords, emailToMatch, pageIndex, pageSize);
        }

        public System.Web.Security.MembershipUserCollection FindUsersByName(out int totalRecords, string usernameToMatch, int pageIndex, int pageSize)
        {
            return base.Channel.FindUsersByName(out totalRecords, usernameToMatch, pageIndex, pageSize);
        }

        public System.Web.Security.MembershipUserCollection GetAllUsers(out int totalRecords, int pageIndex, int pageSize)
        {
            return base.Channel.GetAllUsers(out totalRecords, pageIndex, pageSize);
        }
        
        public int GetNumberOfUsersOnline() {
            return base.Channel.GetNumberOfUsersOnline();
        }
        
        public string GetPassword(string username, string passwordAnswer) {
            return base.Channel.GetPassword(username, passwordAnswer);
        }

        public System.Web.Security.MembershipUser GetUser(string username, bool userIsOnline)
        {
            return base.Channel.GetUser(username, userIsOnline);
        }

        public System.Web.Security.MembershipUser GetUserByProviderUserKey(object providerUserKey, bool userIsOnline)
        {
            return base.Channel.GetUserByProviderUserKey(providerUserKey, userIsOnline);
        }
        
        public string GetUserNameByEmail(string email) {
            return base.Channel.GetUserNameByEmail(email);
        }
        
        public int GetMaxInvalidPasswordAttempts() {
            return base.Channel.GetMaxInvalidPasswordAttempts();
        }
        
        public int GetMinRequiredNonAlphanumericCharacters() {
            return base.Channel.GetMinRequiredNonAlphanumericCharacters();
        }
        
        public int GetMinRequiredPasswordLength() {
            return base.Channel.GetMinRequiredPasswordLength();
        }
        
        public int GetPasswordAttemptWindow() {
            return base.Channel.GetPasswordAttemptWindow();
        }

        public System.Web.Security.MembershipPasswordFormat GetPasswordFormat()
        {
            return base.Channel.GetPasswordFormat();
        }
        
        public string GetPasswordStrengthRegularExpression() {
            return base.Channel.GetPasswordStrengthRegularExpression();
        }
        
        public bool GetRequiresQuestionAndAnswer() {
            return base.Channel.GetRequiresQuestionAndAnswer();
        }
        
        public bool GetRequiresUniqueEmail() {
            return base.Channel.GetRequiresUniqueEmail();
        }
        
        public string ResetPassword(string username, string answer) {
            return base.Channel.ResetPassword(username, answer);
        }
        
        public bool UnlockUser(string userName) {
            return base.Channel.UnlockUser(userName);
        }

        public void UpdateUser(System.Web.Security.MembershipUser user)
        {
            base.Channel.UpdateUser(user);
        }
    }
}

