//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraticeManagement.ExpenseCategoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExpenseCategoryService.IExpenseCategoryService")]
    public interface IExpenseCategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseCategoryService/GetCategoryList", ReplyAction="http://tempuri.org/IExpenseCategoryService/GetCategoryListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataTransferObjects.DataAccessFault), Action="http://tempuri.org/IExpenseCategoryService/GetCategoryListDataAccessFaultFault", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObjects")]
        DataTransferObjects.ExpenseCategory[] GetCategoryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseCategoryService/SaveExpenseCategoryDetail", ReplyAction="http://tempuri.org/IExpenseCategoryService/SaveExpenseCategoryDetailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataTransferObjects.DataAccessFault), Action="http://tempuri.org/IExpenseCategoryService/SaveExpenseCategoryDetailDataAccessFau" +
            "ltFault", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObjects")]
        void SaveExpenseCategoryDetail(DataTransferObjects.ExpenseCategory category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseCategoryService/DeleteExpenseCategory", ReplyAction="http://tempuri.org/IExpenseCategoryService/DeleteExpenseCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DataTransferObjects.DataAccessFault), Action="http://tempuri.org/IExpenseCategoryService/DeleteExpenseCategoryDataAccessFaultFa" +
            "ult", Name="DataAccessFault", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObjects")]
        void DeleteExpenseCategory(DataTransferObjects.ExpenseCategory category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpenseCategoryServiceChannel : PraticeManagement.ExpenseCategoryService.IExpenseCategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpenseCategoryServiceClient : System.ServiceModel.ClientBase<PraticeManagement.ExpenseCategoryService.IExpenseCategoryService>, PraticeManagement.ExpenseCategoryService.IExpenseCategoryService {
                
        public ExpenseCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpenseCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTransferObjects.ExpenseCategory[] GetCategoryList() {
            return base.Channel.GetCategoryList();
        }
        
        public void SaveExpenseCategoryDetail(DataTransferObjects.ExpenseCategory category) {
            base.Channel.SaveExpenseCategoryDetail(category);
        }
        
        public void DeleteExpenseCategory(DataTransferObjects.ExpenseCategory category) {
            base.Channel.DeleteExpenseCategory(category);
        }
    }
}

