CREATE UNIQUE NONCLUSTERED INDEX [IND_ProjGroup_ClientName]
    ON [dbo].[ProjectGroup]([ClientId] ASC, [Name] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];


