CREATE UNIQUE NONCLUSTERED INDEX [IX_MSBadge_Index1] ON [dbo].[MSBadge]
([PersonId] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
ON [PRIMARY];


