CREATE NONCLUSTERED INDEX [IX_PersonCalendarAuto]
    ON [dbo].[PersonCalendarAuto]([PersonId] ASC, [DayOff] ASC, [Date] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];


