CREATE UNIQUE NONCLUSTERED INDEX [IX_PersonName]
    ON [dbo].[Person]([LastName] ASC, [FirstName] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];


