CREATE NONCLUSTERED INDEX [IX_PersonAlias]
    ON [dbo].[Person]([Alias] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];


