CREATE NONCLUSTERED INDEX [IX_TimeEntryHours_TimeEntryId]
    ON [dbo].[TimeEntryHours] ([TimeEntryId] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];
