CREATE UNIQUE NONCLUSTERED INDEX [UN_ProjectNumber]
    ON [dbo].[Project]([ProjectNumber] ASC) WITH ( DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];


