//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRMAProjectedEmailNotifier.ConfigurationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailTemplate", Namespace="http://schemas.datacontract.org/2004/07/DataTransferObjects")]
    [System.SerializableAttribute()]
    public partial class EmailTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigurationService.IConfigurationService")]
    public interface IConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetAllEmailTemplates", ReplyAction="http://tempuri.org/IConfigurationService/GetAllEmailTemplatesResponse")]
        PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate[] GetAllEmailTemplates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/UpdateEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/UpdateEmailTemplateResponse")]
        bool UpdateEmailTemplate(PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/AddEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/AddEmailTemplateResponse")]
        bool AddEmailTemplate(PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/DeleteEmailTemplate", ReplyAction="http://tempuri.org/IConfigurationService/DeleteEmailTemplateResponse")]
        bool DeleteEmailTemplate(int templateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/CheckProjectedProjects", ReplyAction="http://tempuri.org/IConfigurationService/CheckProjectedProjectsResponse")]
        void CheckProjectedProjects(int templateId, string companyName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IConfigurationServiceChannel : PRMAProjectedEmailNotifier.ConfigurationService.IConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<PRMAProjectedEmailNotifier.ConfigurationService.IConfigurationService>, PRMAProjectedEmailNotifier.ConfigurationService.IConfigurationService {
        
        public ConfigurationServiceClient() {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate[] GetAllEmailTemplates() {
            return base.Channel.GetAllEmailTemplates();
        }
        
        public bool UpdateEmailTemplate(PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate template) {
            return base.Channel.UpdateEmailTemplate(template);
        }
        
        public bool AddEmailTemplate(PRMAProjectedEmailNotifier.ConfigurationService.EmailTemplate template) {
            return base.Channel.AddEmailTemplate(template);
        }
        
        public bool DeleteEmailTemplate(int templateId) {
            return base.Channel.DeleteEmailTemplate(templateId);
        }
        
        public void CheckProjectedProjects(int templateId, string companyName) {
            base.Channel.CheckProjectedProjects(templateId, companyName);
        }
    }
}

