//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraticeManagement.PersonStatusService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonStatusService.IPersonStatusService")]
    public interface IPersonStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonStatusService/GetPersonStatuses", ReplyAction="http://tempuri.org/IPersonStatusService/GetPersonStatusesResponse")]
        DataTransferObjects.PersonStatus[] GetPersonStatuses();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonStatusServiceChannel : PraticeManagement.PersonStatusService.IPersonStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonStatusServiceClient : System.ServiceModel.ClientBase<PraticeManagement.PersonStatusService.IPersonStatusService>, PraticeManagement.PersonStatusService.IPersonStatusService {
        
        public PersonStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTransferObjects.PersonStatus[] GetPersonStatuses() {
            return base.Channel.GetPersonStatuses();
        }
    }
}

