<?xml version="1.0" encoding="utf-8"?>
<Database Name="PracticeManagement" EntityNamespace="TestEntities" Class="DataAccessClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=PracticeManagement;Integrated Security=True" SettingsObjectName="DataAccessTest.Properties.Settings" SettingsPropertyName="connection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Storage="_Name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="PTODaysPerAnnum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TerminationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVARCHAR(40) NOT NULL" CanBeNull="false" />
      <Column Name="PersonStatusId" Type="System.Int32" CanBeNull="false" />
      <Column Name="EmployeeNumber" Type="System.String" CanBeNull="false" />
      <Association Name="Person_Client" Member="Clients" OtherKey="DefaultSalespersonID" Type="Client" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DefaultDiscount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultTerms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DefaultSalespersonID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Inactive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Person_Client" Member="Person" ThisKey="DefaultSalespersonID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
</Database>
