CREATE TABLE [dbo].[Domain]
(
	ID			INT	IDENTITY (1, 1) NOT NULL,
	Name		NVARCHAR(100)	NOT NULL,
	SortOrder	INT			NOT NULL,
	CONSTRAINT PK_Domain_ID PRIMARY KEY CLUSTERED(ID),
	CONSTRAINT [UQ_Domain_Name] UNIQUE NONCLUSTERED(Name)
)

