//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number with 3 decimal digits is allowed for the Amount..
        /// </summary>
        internal static string AmountThreeDigits {
            get {
                return ResourceManager.GetString("AmountThreeDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A number with 2 decimal digits is allowed for the Amount..
        /// </summary>
        internal static string AmountTwoDigits {
            get {
                return ResourceManager.GetString("AmountTwoDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update time entry: there&apos;s no such command..
        /// </summary>
        internal static string btnUpdateTE_CommandValue {
            get {
                return ResourceManager.GetString("btnUpdateTE_CommandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot {0} milesone person details because there (s)he has reported hours related to it..
        /// </summary>
        internal static string CannotModifyMilestonePerson {
            get {
                return ResourceManager.GetString("CannotModifyMilestonePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved successfully.
        /// </summary>
        internal static string DataSavedSuccessfully {
            get {
                return ResourceManager.GetString("DataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A date must be between {0} and {1}..
        /// </summary>
        internal static string DateRangeMessage {
            get {
                return ResourceManager.GetString("DateRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following people designate this person as their manager: {0}.&amp;nbsp; Please select a new manager for all people previously using this person as their manager..
        /// </summary>
        internal static string DesignatePersonAsManager {
            get {
                return ResourceManager.GetString("DesignatePersonAsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person with this email already exists. Please review existing users to make sure there isn&apos;t a duplicate entry, and enter a different email address if necessary..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists. Please enter a different user name..
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding time entry: {0}.
        /// </summary>
        internal static string Exception_ErrorAddindTimeEntry {
            get {
                return ResourceManager.GetString("Exception_ErrorAddindTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating time entry: {0}.
        /// </summary>
        internal static string Exception_ErrorUpdatingTimeEntry {
            get {
                return ResourceManager.GetString("Exception_ErrorUpdatingTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such command.
        /// </summary>
        internal static string Exception_NoSuchCommand {
            get {
                return ResourceManager.GetString("Exception_NoSuchCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidAnswer {
            get {
                return ResourceManager.GetString("InvalidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entry date for this project-milestone should be between {0} and {1}.
        /// </summary>
        internal static string InvalidMilestoneDate {
            get {
                return ResourceManager.GetString("InvalidMilestoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Milestone ID was not specified properly..
        /// </summary>
        internal static string InvalidMilestoneId {
            get {
                return ResourceManager.GetString("InvalidMilestoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month number must be between {0} and {1}..
        /// </summary>
        internal static string InvalidMonthNumber {
            get {
                return ResourceManager.GetString("InvalidMonthNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of years must be a positive integer which is not greater then the current year..
        /// </summary>
        internal static string InvalidNumberOfYears {
            get {
                return ResourceManager.GetString("InvalidNumberOfYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidQuestion {
            get {
                return ResourceManager.GetString("InvalidQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year must be between {0} and {1}..
        /// </summary>
        internal static string InvalidYearNumber {
            get {
                return ResourceManager.GetString("InvalidYearNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Career Manager is set..
        /// </summary>
        internal static string ManagerSet {
            get {
                return ResourceManager.GetString("ManagerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone person details saved successfully..
        /// </summary>
        internal static string MilestonePersonSaved {
            get {
                return ResourceManager.GetString("MilestonePersonSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone saved successfully..
        /// </summary>
        internal static string MilestoneSavedMessage {
            get {
                return ResourceManager.GetString("MilestoneSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only active persons are allowed to allowed to record time entries. Please contact your administrator for more details..
        /// </summary>
        internal static string NotAllowedToRecordTE {
            get {
                return ResourceManager.GetString("NotAllowedToRecordTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Termination Date for Active person must be Empty.
        /// </summary>
        internal static string PersonDetail_custTerminationDateMustBeEmpty {
            get {
                return ResourceManager.GetString("PersonDetail_custTerminationDateMustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is not assigned to any milestones during the period selected..
        /// </summary>
        internal static string PersonIsNotAssgned {
            get {
                return ResourceManager.GetString("PersonIsNotAssgned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons highlighted in red have their start dates greater than the milestone start date..
        /// </summary>
        internal static string PersonsStartGreaterMilestoneStart {
            get {
                return ResourceManager.GetString("PersonsStartGreaterMilestoneStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other projects also exist for this account, but your permissions do not allow you to see them..
        /// </summary>
        internal static string ProjectsListSecure {
            get {
                return ResourceManager.GetString("ProjectsListSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        internal static string ProviderError {
            get {
                return ResourceManager.GetString("ProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} details are saved successfully..
        /// </summary>
        internal static string SavedDetailsConfirmation {
            get {
                return ResourceManager.GetString("SavedDetailsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session state is unavailable here..
        /// </summary>
        internal static string SessionStateUnavailable {
            get {
                return ResourceManager.GetString("SessionStateUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entry added successfully..
        /// </summary>
        internal static string TimeEntryAddedSuccessfully {
            get {
                return ResourceManager.GetString("TimeEntryAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entry updated successfully..
        /// </summary>
        internal static string TimeEntryUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TimeEntryUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save the data to view the result..
        /// </summary>
        internal static string UnableCalculateCods {
            get {
                return ResourceManager.GetString("UnableCalculateCods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to enter activity for the date {0} (Start: {1}, End: {2}). Check if it&apos;s not a vacation or a day-off..
        /// </summary>
        internal static string UnableToFindDateIndex {
            get {
                return ResourceManager.GetString("UnableToFindDateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        internal static string UserRejected {
            get {
                return ResourceManager.GetString("UserRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please note that this person has {0} vacation day(s) scheduled during the period you have selected. These vacation days have not been considered in the calculations on this page..
        /// </summary>
        internal static string VacationIncluded {
            get {
                return ResourceManager.GetString("VacationIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to calculate values. Please check, if the person has active compensation record..
        /// </summary>
        internal static string WhatIfError {
            get {
                return ResourceManager.GetString("WhatIfError", resourceCulture);
            }
        }
    }
}

